version: '3'
services: 
  server:
    build: ./server
    ports: 
      - 3001:3001
      - 4000:4000
    networks: 
      - local


  client:
    build: ./client
    ports: 
      - 3000:3000
    networks: 
      - local


networks: 
  local:
    driver: bridge